#端口号
server:
  port: 8001


spring:
  application:
    #微服务名称,也是入驻进Eureka服务器的名称
    name: cloud-payment-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.dyy.springcloud.entities  #所有Entity别名类所在包

eureka:
  client:
    #表示是否将自己注册进EurekaServer，默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka  #单机版，即只有一个eureka注册中心时
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #集群版，即有多个（现在是两个）eureka注册中心时
  instance:
    #在eureka上注册的主机名称修改如下，原来是 DESKTOP-KNLUAJ7:cloud-payment-service，修改后是payment8001
    instance-id: payment8001
    prefer-ip-address: true #访问路径可以显示ip地址
#    #从客户端来关闭自我保护机制
#    #eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
#    lease-renewal-interval-in-seconds: 1
#    #eureka服务端在收到最后一次心跳后等待时间上限，单位是秒(默认是90秒)，超时将剔除服务
#    lease-expiration-duration-in-seconds: 2