server:
  port: 8004
spring:
  application:
    #服务名称，即注册zookeeper到服务中心的名称
    name: cloud-provider-payment
  cloud:
    zookeeper:
      #某zookeeper机器的ip+端口号
      connect-string: 222.20.83.207:2181
